bitcoind:
  image: seegno/bitcoind:0.11
  command:
    -datadir=/var/lib/bitcoind
    -regtest=1
    -rest
    -rpcallowip=10.211.0.0/16
    -rpcallowip=172.17.0.0/16
    -rpcpassword=bar
    -rpcuser=foo
    -server
  ports:
    - 18332:18332

bitcoindssl:
  image: seegno/bitcoind:0.11
  command:
    -datadir=/var/lib/bitcoind
    -regtest=1
    -rest
    -rpcallowip=10.211.0.0/16
    -rpcallowip=172.17.0.0/16
    -rpcpassword=bar
    -rpcssl
    -rpcsslcertificatechainfile=/etc/ssl/bitcoind/server.cert
    -rpcsslprivatekeyfile=/etc/ssl/bitcoind/server.pem
    -rpcuser=foo
    -server
  ports:
    - 18333:18332
  volumes:
    - ./test/config/ssl:/etc/ssl/bitcoind

app:
  build: .
  links:
    - bitcoind
    - bitcoindssl
